---
title: "27_04_23_Model_MH"
subtitle: "Modeling forecast count for MH"
execute: 
  message: false
  echo: true
  warning: false
  error: true

format: 
  html:
    self-contained: true
    code-line-numbers: true

custom_title_page: false
filters:
  - lightbox
lightbox: auto
---

### Log
> Version 2023-03-29.   
Code was initially made in SAS and send by ___Jemisha Apajee___. 
File Name: "Analysis_common_diseases_step_by_step_20221123.sas"

> Version 2023-04-19   
Translated to R by ___Javier Silva-Valencia___, adapted to Mental Health paper

> Version 2023-05-17   
Whitout social problems

### Context/Notes

- This is part of a mental health paper, where we are analyzing the amount of MH-related visits among several countries (countries part of INTREPID) in a pre and during pandemic period.

- The main variables are: Amount of total visits, amount of visits related to MH, 7-9 categories of MH groups, Tipe of visit(in-person, virtual) all this by month from 2018 to 2021 (Except Perú that has data from 2019-2021)

- ___This specific code___ is for creating a model that fits the time series and creating a forecast to compare prepandemic and pandemic trend.

```{r}
i <- 2
countryc <- c("prueba", "prueba2", "prueba3")
```

- **Country:** `r countryc[i]`